### ISSUE TITLE
看到说副图部分开放完毕 但是好像没有成交量的图

### ISSUE THREAD

**Issue by rtyheji** [Tophold/FinancialCustomerView#24]
Demo 只有macd 的指标图没有成交量的图。。

**Comment by scsfwgy** [comment]
对，还没加。主要原因，这个成交量需要有具体的业务数据才可以进行。而其他指标只要有开闭高地价就可以处理。

**Comment by rtyheji** [comment]
能弱弱的问下 这个框库大概啥时候能完成呢

**Comment by scsfwgy** [comment]
现在遇到一个问题，就是主图和副图融合的时候代码层次有点不太好整。另外，工作还比较忙。尽量五月底完成吧。

**Comment by scsfwgy** [comment]
为什么没有成交量：现在已开发的部分的各种指标要求一个数据单元只包括：开盘价、收盘价、最低价、最高价、时间戳。而成交量需要额外的单独数据，并不通用。这个需求量挺大的，会在下一个版本加上成交量。

**Comment by kejunlu** [comment]
@scsfwgy  副图部分会加各种指标吗？

**Comment by scsfwgy** [comment]
会。最近一直在思考如何对副图指标抽象化，可以灵活扩展各种副图指标而不是写死。

**Comment by scsfwgy** [comment]
@rtyheji @kejunlu 量图已经添加，可以看一下有什么问题没 🌹

 https://github.com/Tophold/FinancialCustomerView/tree/feature_vol

**Comment by scsfwgy** [comment]
只有在“去看数字货币demo”中可以查看demo.
